### ISSUE TITLE
Hearthstone // Itemspell

### ISSUE THREAD

**Issue by slash-design** [dufernst/LegionCore-7.3.5#178]
If you use the hearthstone, other players will not see the spell.
Does not only affect the hearthstone. It affects all items with spells.

**Comment by slash-design** [comment]
I think the error is in the Player.cpp at CastItemUseSpell
The triggerdatas are the problem

**Comment by randiel123** [comment]
> I think the error is in the Player.cpp at CastItemUseSpell The triggerdatas are the problem

Have you been able to fix it?

**Comment by slash-design** [comment]
Well, unfortunately not quite yet.
I have managed to get the spells to be displayed for all other players, but the items are no longer scored. This means that if you drink water, for example, and you have 20 of it, the counter doesn't go down any further. Instead of 19 items, the item remains at 20 items.

By the way. The fact that the spells are not displayed does not only apply to Hearthstone, but to all magic items. Items in quests... etc. 

Does anyone have an idea to fix it correctly ?

**Comment by randiel123** [comment]
> Well, unfortunately not quite yet. I have managed to get the spells to be displayed for all other players, but the items are no longer scored. This means that if you drink water, for example, and you have 20 of it, the counter doesn't go down any further. Instead of 19 items, the item remains at 20 items.
> 
> By the way. The fact that the spells are not displayed does not only apply to Hearthstone, but to all magic items. Items in quests... etc.
> 
> Does anyone have an idea to fix it correctly ?


Ok, now I'll check to see what I can do and pass solution. You had said that the problem was in the TriggerData right?

**Comment by slash-design** [comment]
Well, at least I think so.
I looked it up on TrinityCore.
From there I got the ServerCastId and ClientCastId. This can be found in the Player.cpp under

void Player::CastItemUseSpell

The CastId must also be added to the ScriptMgr.

Then it has at least shown the spell for all players, but unfortunately the items are no longer counted -.-

**Comment by randiel123** [comment]
> Well, at least I think so. I looked it up on TrinityCore. From there I got the ServerCastId and ClientCastId. This can be found in the Player.cpp under
> 
> void Player::CastItemUseSpell
> 
> The CastId must also be added to the ScriptMgr.
> 
> Then it has at least shown the spell for all players, but unfortunately the items are no longer counted -.-

Ok, well I'll check that out and see how I fix it, I already have an idea of ​​how I can fix it. When I solve it, I'll send you the solution here.

**Comment by slash-design** [comment]
That would of course be super nice of you :-)

**Comment by randiel123** [comment]
Well, I've tried several times and I still haven't found the solution. I have compiled the TrinityCore server and deleted its ServerCastId and ClientCastId lines but still in Trinitycore, even if you delete those lines, the item's ability is still visible in the others. I don't know whether to give up or continue xd

**Comment by slash-design** [comment]
I currently feel the same way :-)
I'll have another look when I've finished with the garrisons. But maybe you or someone else has an idea for a solution :-) As I said, I suspect it's the TriggerDatas. It's just very annoying because you can never see what another player is currently doing :-)

**Comment by slash-design** [comment]
@dufernst Do you have any idea where the problem could be?

**Comment by ReyDonovan** [comment]
HandleUseItemOpcode

**Comment by slash-design** [comment]
And what do you think is the error there?

**Comment by ReyDonovan** [comment]
you need to look towards the handler

**Comment by slash-design** [comment]
I've already tried that too.
I have changed everything there to “TrinityCore-Like”. 
No success.

![grafik](https://github.com/dufernst/LegionCore-7.3.5/assets/108064015/013365da-7f2e-4679-bac2-b0bc73b86c6e)

**Comment by slash-design** [comment]
**Update:**
It has something to do with the m_SpellVisual in the Spell.cpp.

The following code is stored there under Spell::prepare:

    if (!m_SpellVisual)
        m_SpellVisual = m_spellInfo->GetSpellXSpellVisualId(m_caster, m_targets.GetUnitTarget() ? m_targets.GetUnitTarget() : m_caster);


If you remove this code, no spell appears at all.
If you type in .cast 8690 (Hearthstone) then it starts the spell, but does not display the visual.
If you click on the hearthstone (item 6948) in your bag, it also casts the spell, but does not display anything.
So the error must have something to do with the SpellVisual......

**Comment by ReyDonovan** [comment]
Hm seems like old bug tc

**Comment by Fragrus** [comment]
I looked at the problem a little. If you set the combat log to full logging, then the second client (observer) will not even receive a message in the combat log that someone has started casting a spell. Therefore, the issue is not in the visual part, but in general in the fact that other clients do not receive information that someone has started casting a spell when using an item.

**Comment by Fragrus** [comment]
Yes, sir. I researched this topic. I have no idea why there are so many such small schools in this kernel, but they appear here and there. As I expected, the other client was receiving incorrect data. This is due to spellCastData and the SMSG_SPELL_START package. The GUID order is mixed up there. In fact, I have no idea why this even worked for all the other spells, but here we are.
In this core we have this: https://github.com/dufernst/LegionCore-7.3.5/blob/bf7199a73c99b4e62f5444aa862ba864cd553dbb/src/server/game/Server/Packets/SpellPackets.cpp#L486
In TC it is: https://github.com/TrinityCore/TrinityCore/blob/31f6ba5a92b0f88f328e0e6adcf33bd4820599c2/src/server/game/Server/Packets/SpellPackets.cpp#L360
I think comments are unnecessary.
```
 data << spellCastData.CasterUnit;
 data << spellCastData.CasterGUID;
```
change to:
```
 data << spellCastData.CasterGUID;
 data << spellCastData.CasterUnit;
```
I was already assembling the kernel in Debug mode, but I was lucky that I thought of running the sniffer and climbed in to see how the package was being formed.
If you're not too lazy, please make a pull request for this issue.

![изображение](https://github.com/dufernst/LegionCore-7.3.5/assets/26599635/ad741567-47f7-445f-a0b7-c848787e9c71)

**Comment by slash-design** [comment]
@Fragrus 

I have exactly one more thing to say....
I love you :-)

Thank you 1000 times for this fix :-)

**Comment by dufernst** [comment]
@Fragrus thanks again for the fix :+1: 
And @slash-design thanks for confirming. :+1:
