### ISSUE TITLE
what is boost version?

### ISSUE THREAD

**Issue by rakikhun** [dufernst/LegionCore-7.3.5#2]
hey buddy . what is boost version and visual version @dufernst

**Comment by dufernst** [comment]
@rakikhun according to the cmake files boost 1.64 or higher is required, maybe it also works with a lower version (if you change dep/boost/CMakeLists.txt) but I have not tested that.
Visual Studio 2017 and 2019 (maybe also 2015, not tested) should both be fine (when patched).
A change that I will be pushing soon will require C++17 support, so that is why you need to make sure your VS is using a recent patch.

**Comment by rakikhun** [comment]
I compile with Visual Studio 2017 and boost 1.64 
-error.log = Unknown compiler version - please run the configure tests and report the results

DBC maps map etc do you have a chance to share them ?

**Comment by dufernst** [comment]
You can use the DBC/maps/etc from this forum thread:
https://www.emucoach.com/legion-7-3-5-/6945-repack-7-3-5-legion-wow-repack-wow-legion-7-3-5-repack-blizzlike-fun.html
Those are the only ones that work, I do not know if there is a generator available that is able to recreate these.

Regarding the compiler:
In cmake/compiler/mscvc/settings.cmake you can find the checks regarding the compiler.

**Comment by rakikhun** [comment]
you're amazing. thanks. 👑

**Comment by dufernst** [comment]
No problem, and if you run into any issues, feel free to let me know.
I might want fix it anyway, and a good bug report is always welcome.
