### ISSUE TITLE
SmartScripts for Creatures (using GUID in world.smart_scripts table)

### ISSUE THREAD

**Issue by Axdrell** [dufernst/LegionCore-7.3.5#81]
Adding a smart script for a creature (using for example "-2000" for a creature with guid id 2000") does not result in the creature using the smart-script. SmartAI works for creature entries under world.creature_template table.

I have a creature (in the world.creature table) with guid 264561 and added a simple record (guid -264561) in world.smart_script for a Talk emote. No creature action and no error in debug logs.

Will check the code to resolve this, unless someone can share a quick fix. 

Thanks so much.

Axdrell

**Comment by Axdrell** [comment]
What do you mean?

**Comment by qqwqqwe** [comment]
its relate the table



---Original---
From: ***@***.***&gt;
Date: Wed, May 11, 2022 00:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dufernst/LegionCore-7.3.5] SmartScripts for Creatures (usingGUID in world.smart_scripts table) (Issue #81)




 
What do you mean?

**Comment by Axdrell** [comment]
Smart_Scripts work fine for creatures under the creature_template/creature_template_wdb tables. 

The problem is with the creatures listed under the creature table. If you setup a negative entry in smart_scripts for a creature record under the creature table, the creature will not execute the smart_script (for example an emote).

**Comment by qqwqqwe** [comment]
Wdb 230000 and so on miss in the table and report error&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, May 11, 2022 01:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dufernst/LegionCore-7.3.5] SmartScripts for Creatures (using GUID in world.smart_scripts table) (Issue #81)




 
Smart_Scripts work fine for creatures under the creature_template/creature_template_wdb tables.
 
The problem is with the creatures listed under the creature table. If you setup a negative entry in smart_scripts for a creature record under the creature table, the creature will not execute the smart_script (for example an emote).

**Comment by Axdrell** [comment]
You can close this. The code is working. The problem was my creature record settings.

**Comment by qqwqqwe** [comment]
Close yourself and Dufernst, other people cannot Close.
